import type { Category, Product, ProductImage, ProductVariant, VariantOption } from "./database-types"

// Categorías
export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Cake Toppers",
    slug: "cake-toppers",
    description: "Decoraciones para tortas de todos los temas",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "cat-2",
    name: "Banderines",
    slug: "banderines",
    description: "Guirnaldas y banderines decorativos",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "cat-3",
    name: "Souvenirs y Sorpresitas",
    slug: "souvenirs-sorpresitas",
    description: "Cajitas, bolsitas y sorpresas para invitados",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "cat-4",
    name: "Sets Temáticos",
    slug: "sets-tematicos",
    description: "Kits completos para decorar tu fiesta",
    created_at: new Date(),
    updated_at: new Date(),
  },
]

// Productos (ejemplos con variantes)
export const products: Product[] = [
  // Cake Toppers
  {
    id: "prod-ct-1",
    category_id: "cat-1",
    name: "Cake Topper Personalizable",
    description: "Topper personalizado con el nombre y edad que desees",
    base_price: 4500,
    is_customizable: true,
    mercadolibre_url: null,
    whatsapp_url: null,
    subcategory: "Personalizado",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "prod-ct-2",
    category_id: "cat-1",
    name: "Topper Unicornio (Set x6)",
    description: "Set de 6 toppers temáticos de unicornios en diferentes colores",
    base_price: 3800,
    is_customizable: false,
    mercadolibre_url: "https://mercadolibre.com.ar/producto-unicornio",
    whatsapp_url: "https://wa.me/c/5491112345678",
    subcategory: "Temático",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "prod-ct-3",
    category_id: "cat-1",
    name: "Topper Números",
    description: "Números decorativos para tortas, disponibles en varios colores y acabados",
    base_price: 2500,
    is_customizable: false,
    mercadolibre_url: "https://mercadolibre.com.ar/producto-numeros",
    whatsapp_url: "https://wa.me/c/5491112345678",
    subcategory: "Números",
    created_at: new Date(),
    updated_at: new Date(),
  },
  // Banderines
  {
    id: "prod-ba-1",
    category_id: "cat-2",
    name: "Banderín Personalizable",
    description: "Banderín personalizado con el mensaje que desees",
    base_price: 5200,
    is_customizable: true,
    mercadolibre_url: null,
    whatsapp_url: null,
    subcategory: "Personalizado",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "prod-ba-2",
    category_id: "cat-2",
    name: "Guirnalda Feliz Cumpleaños",
    description: "Guirnalda clásica de feliz cumpleaños en diferentes colores",
    base_price: 4200,
    is_customizable: false,
    mercadolibre_url: "https://mercadolibre.com.ar/producto-guirnalda",
    whatsapp_url: "https://wa.me/c/5491112345678",
    subcategory: "Clásico",
    created_at: new Date(),
    updated_at: new Date(),
  },
]

// Imágenes de productos
export const productImages: ProductImage[] = [
  // Cake Topper Personalizable - múltiples imágenes
  {
    id: "img-1",
    product_id: "prod-ct-1",
    image_url: "/custom-cake-topper-colorful.jpg",
    display_order: 1,
    alt_text: "Cake topper personalizable vista frontal",
    created_at: new Date(),
  },
  {
    id: "img-2",
    product_id: "prod-ct-1",
    image_url: "/custom-cake-topper-gold.jpg",
    display_order: 2,
    alt_text: "Cake topper personalizable dorado",
    created_at: new Date(),
  },
  {
    id: "img-3",
    product_id: "prod-ct-1",
    image_url: "/custom-cake-topper-silver.jpg",
    display_order: 3,
    alt_text: "Cake topper personalizable plateado",
    created_at: new Date(),
  },
  // Topper Unicornio - múltiples imágenes
  {
    id: "img-4",
    product_id: "prod-ct-2",
    image_url: "/unicorn-cake-toppers-colorful.jpg",
    display_order: 1,
    alt_text: "Set de toppers de unicornio",
    created_at: new Date(),
  },
  {
    id: "img-5",
    product_id: "prod-ct-2",
    image_url: "/unicorn-cake-toppers-pink.jpg",
    display_order: 2,
    alt_text: "Toppers de unicornio rosados",
    created_at: new Date(),
  },
  {
    id: "img-6",
    product_id: "prod-ct-2",
    image_url: "/unicorn-cake-toppers-rainbow.jpg",
    display_order: 3,
    alt_text: "Toppers de unicornio arcoíris",
    created_at: new Date(),
  },
  // Topper Números
  {
    id: "img-7",
    product_id: "prod-ct-3",
    image_url: "/golden-number-cake-topper.jpg",
    display_order: 1,
    alt_text: "Números dorados para torta",
    created_at: new Date(),
  },
  {
    id: "img-8",
    product_id: "prod-ct-3",
    image_url: "/silver-number-cake-topper.jpg",
    display_order: 2,
    alt_text: "Números plateados para torta",
    created_at: new Date(),
  },
  {
    id: "img-9",
    product_id: "prod-ct-3",
    image_url: "/pink-glitter-number-cake-topper.jpg",
    display_order: 3,
    alt_text: "Números con glitter rosa",
    created_at: new Date(),
  },
]

// Variantes de productos
export const productVariants: ProductVariant[] = [
  // Variantes para Topper Unicornio
  {
    id: "var-1",
    product_id: "prod-ct-2",
    name: "Color",
    type: "button",
    is_required: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "var-2",
    product_id: "prod-ct-2",
    name: "Tamaño",
    type: "select",
    is_required: true,
    display_order: 2,
    created_at: new Date(),
  },
  // Variantes para Topper Números
  {
    id: "var-3",
    product_id: "prod-ct-3",
    name: "Acabado",
    type: "button",
    is_required: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "var-4",
    product_id: "prod-ct-3",
    name: "Número",
    type: "select",
    is_required: true,
    display_order: 2,
    created_at: new Date(),
  },
  // Variantes para Guirnalda
  {
    id: "var-5",
    product_id: "prod-ba-2",
    name: "Color",
    type: "button",
    is_required: true,
    display_order: 1,
    created_at: new Date(),
  },
]

// Opciones de variantes
export const variantOptions: VariantOption[] = [
  // Opciones de Color para Topper Unicornio
  {
    id: "opt-1",
    variant_id: "var-1",
    name: "Rosa",
    price_modifier: 0,
    stock_quantity: 15,
    is_available: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "opt-2",
    variant_id: "var-1",
    name: "Arcoíris",
    price_modifier: 200,
    stock_quantity: 10,
    is_available: true,
    display_order: 2,
    created_at: new Date(),
  },
  {
    id: "opt-3",
    variant_id: "var-1",
    name: "Dorado",
    price_modifier: 300,
    stock_quantity: 8,
    is_available: true,
    display_order: 3,
    created_at: new Date(),
  },
  // Opciones de Tamaño para Topper Unicornio
  {
    id: "opt-4",
    variant_id: "var-2",
    name: "Pequeño (10cm)",
    price_modifier: 0,
    stock_quantity: 20,
    is_available: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "opt-5",
    variant_id: "var-2",
    name: "Mediano (15cm)",
    price_modifier: 500,
    stock_quantity: 15,
    is_available: true,
    display_order: 2,
    created_at: new Date(),
  },
  {
    id: "opt-6",
    variant_id: "var-2",
    name: "Grande (20cm)",
    price_modifier: 1000,
    stock_quantity: 10,
    is_available: true,
    display_order: 3,
    created_at: new Date(),
  },
  // Opciones de Acabado para Topper Números
  {
    id: "opt-7",
    variant_id: "var-3",
    name: "Dorado",
    price_modifier: 0,
    stock_quantity: 50,
    is_available: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "opt-8",
    variant_id: "var-3",
    name: "Plateado",
    price_modifier: 0,
    stock_quantity: 50,
    is_available: true,
    display_order: 2,
    created_at: new Date(),
  },
  {
    id: "opt-9",
    variant_id: "var-3",
    name: "Glitter Rosa",
    price_modifier: 300,
    stock_quantity: 30,
    is_available: true,
    display_order: 3,
    created_at: new Date(),
  },
  // Opciones de Número
  {
    id: "opt-10",
    variant_id: "var-4",
    name: "0",
    price_modifier: 0,
    stock_quantity: 20,
    is_available: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "opt-11",
    variant_id: "var-4",
    name: "1",
    price_modifier: 0,
    stock_quantity: 20,
    is_available: true,
    display_order: 2,
    created_at: new Date(),
  },
  // ... más números del 2-9
  // Opciones de Color para Guirnalda
  {
    id: "opt-20",
    variant_id: "var-5",
    name: "Multicolor",
    price_modifier: 0,
    stock_quantity: 25,
    is_available: true,
    display_order: 1,
    created_at: new Date(),
  },
  {
    id: "opt-21",
    variant_id: "var-5",
    name: "Rosa y Dorado",
    price_modifier: 200,
    stock_quantity: 20,
    is_available: true,
    display_order: 2,
    created_at: new Date(),
  },
  {
    id: "opt-22",
    variant_id: "var-5",
    name: "Azul y Plateado",
    price_modifier: 200,
    stock_quantity: 20,
    is_available: true,
    display_order: 3,
    created_at: new Date(),
  },
]
